Нужно больше функций
htmlacademy-javascript/2321527-kekstagram-28 pull request #2
Opened 2023-03-20 13:00 UTC by n-igorevich

---
:mortar_board: [Нужно больше функций](https://up.htmlacademy.ru/javascript/28/user/2321527/tasks/7)

:boom: https://htmlacademy-javascript.github.io/2321527-kekstagram-28/2/

2023-03-23 10:21 UTC, Dima-Dim requested changes
По заданию не нужно править файл html.
Нужно поправить замечания линтера.

2023-03-25 19:01 UTC, craz3r requested changes

2023-03-25 19:01 UTC, craz3r commented on js/main.js
> +    return (true);
Функция должна возвращать true если number >= длине строки

2023-03-25 19:01 UTC, craz3r commented on js/main.js
> +      numberPosition = '';
Ветка else здесь не делает ничего, поэтому ее можно опустить

2023-03-25 19:01 UTC, craz3r commented on js/main.js
> +    return (true);
Если return возвращает простое значение то скобки вокруг него не нужны

2023-03-27 17:24 UTC, merged